f=kamland-notes

#latex:
#	pdflatex $(f).tex pdflatex $(f).tex && latexmk $(f).tex && pdflatex $(f).tex pdflatex $(f).tex

clean:
	rm -rf $(f).aux
	rm -rf $(f).bbl
	rm -rf $(f).blg
	rm -rf $(f).dvi
	rm -rf $(f).fdb_latexmk
	rm -rf $(f).fls
	rm -rf $(f).log
	rm -rf $(f).out
	rm -rf $(f).toc
